init: react-query 초기 세팅을 진행합니다.
TinU-Official/TinU-Client pull request #10
Opened 2024-09-27 21:30 UTC by jungwoo3490

## 🔥 Related Issues

- close #5 

## ✅ 작업 내용

react-query 초기 세팅을 진행했어요.

쿼리 관련 옵션을 지정해주었는데, 주석 참고하면 좋을 것 같아요!!
추가적으로 필요하다고 생각하는 옵션 있으면 제안주셔도 됩니다!

2024-09-28 05:11 UTC, juheehasaeyo requested changes

2024-09-28 05:11 UTC, juheehasaeyo commented on src/App.tsx
> +        refetchOnWindowFocus: false,
window가 focus되었다는 말이 어떤건지 잘 모르겠어요!
설명해주시면 감사하겠숩니다..🙄

2024-09-28 05:15 UTC, jungwoo3490 commented on src/App.tsx
> +        refetchOnWindowFocus: false,
프로젝트가 동작중인 화면을 윈도우라고 해요!! react-query는 기본적으로 윈도우에서 벗어났다가(다른 탭이나 프로그램을 열었다가) 다시 해당 윈도우로 들어왔을 때 리패칭을 하게 돼요. 사실 저희 프로젝트에서 이런 경우를 의도하고 사용할 경우가 없다고 판단해서 해당 기능을 비활성화시킨 부분입니다!

2024-09-28 05:42 UTC, juheehasaeyo commented on src/App.tsx
> +        refetchOnWindowFocus: false,
오옹 확인했습니당 설명 땡큐쏘머지(?)🤩

2024-09-28 05:42 UTC, juheehasaeyo approved these changes

2024-09-30 06:16 UTC, jungwoo3490 commented
🚀🚀🚀

2024-09-30 06:16 UTC, merged