init: GlobalStyle 세팅
TinU-Official/TinU-Client pull request #9
Opened 2024-09-25 14:31 UTC by juheehasaeyo

## 🔥 Related Issues

- close #8 

## ✅ 작업 내용
틴유 프로젝트 글로벌스타일링입니다. 수정사항은 리뷰에 남겨주세요!!
- 폰트 적용은 추후 반영 예정

2024-09-25 14:51 UTC, jungwoo3490 requested changes
고생했어요 🚀🚀🚀
언급한 부분 한 번 확인해주면 좋을 것 같아요!!!

2024-09-25 14:51 UTC, jungwoo3490 commented on src/styles/GlobalStyles.ts
> +  }
하나로 묶어주는 게 좋을 것 같네요!!

2024-09-25 14:51 UTC, jungwoo3490 commented on src/styles/GlobalStyles.ts
> +  }
음 하나로 묶어야 된다고 했었는데, 다시 보니 이건 버튼의 기본 스타일을 초기화하는 css라 gStyle보다는 resetCss 내부로 들어가는게 좋아보이네요!!

2024-09-25 14:51 UTC, jungwoo3490 commented on src/styles/GlobalStyles.ts
> +  }
요고는 왜 들어가있는지 궁금해요!

2024-09-25 14:51 UTC, jungwoo3490 commented on src/styles/GlobalStyles.ts
> +  }
얘도 default 스타일 초기화 코드라서 resetCss로 들어가는게 좋아보입니다!

2024-09-25 14:51 UTC, jungwoo3490 commented on src/styles/GlobalStyles.ts
> +  }
이 부분은 default 스타일 초기화 코드라 resetCss로 들어가는게 좋아보이네요!

2024-09-25 14:51 UTC, jungwoo3490 commented on src/styles/GlobalStyles.ts
> +    max-width: 43rem;
👍🏻👍🏻👍🏻

2024-09-25 14:51 UTC, jungwoo3490 commented on src/styles/GlobalStyles.ts
> +    max-width: 43rem;
위에 이미 지정해둔 속성이라 제거해도 될 것 같네요 :)

2024-09-25 14:51 UTC, jungwoo3490 commented on src/styles/GlobalStyles.ts
> +    font-size: 62.5%;
👍🏻👍🏻👍🏻👍🏻👍🏻

2024-09-26 14:18 UTC, juheehasaeyo commented on src/styles/GlobalStyles.ts
> +  }
`:root`는 CSS에서 가장 상위 레벨의 요소, 즉 `<html>` 태그를 가리킵니다!
`--vh: 100%;`는 화면(뷰포트)의 높이를 100%로 지정해서 이 값은 나중에 CSS에서 사용할 때 var(--vh)로 참조할 수 있는데, 모바일뷰에서 화면 높이가 동적으로 변할때를 대비하여 화면 크기에 맞는 레이아웃을 동적으로 설정할 수 있다고 합니다!!

2024-09-26 18:57 UTC, jungwoo3490 commented on src/styles/GlobalStyles.ts
> +  }
모바일 뷰에서 화면 높이가 동적으로 변하는 이슈에 대응하기 위해 `dvh`라는 단위가 나왔어요!!
https://velog.io/@sanghyeon/CSS-dvh-lvh-svh-dvw-lvw-svw-%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0

`var(--vh)`로 뷰포트 높이를 계산하는 것보다 Outlet에 `height: 100dvh` 로 지정하고 사용하는 게 더 간편할 것 같아서 이 부분은 없어도 된다는 생각입니다!!

2024-09-27 14:10 UTC, jungwoo3490 commented
LGTM 머지합시다!!!
고생했어요!!!!! 🚀🚀🚀

2024-09-27 14:10 UTC, jungwoo3490 approved these changes

2024-09-27 14:18 UTC, merged